workflows:
  mm_repair_android:
    name: MM Repair Android APK
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      java: 17
    scripts:
      - name: Build release APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - $CM_BUILD_OWNER_EMAIL
        notify:
          success: true
          failure: true
