workflows:
  mm_repair_android:
    name: MM Repair Android

    scripts:
      - name: Build debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
